project:
  type: website
  output-dir: docs

website:
  title: "BioSound Exploratory Project"
  sidebar:
    style: "docked"
    search: true
    background: dark
    logo: images/BioSound.png
    contents:
        - text: "Project Overview"
          file: overview.qmd
        - text: "Acoustic Indices"
          file: indices.qmd
        - text: "Data Processing & Management"
          file: data.qmd
        - text: "Evaluating Indices"
          file: analysis.qmd  
        - text: "Recommendations"
          file: recommendations.qmd  

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

