---
title: "BioSound Exploratory Project"
subtitle: "Analytical Documentation"
---

### The BioSound Working Group

The BioSound working group is composed of various scientists and stakeholders interested in producing acoustic-based data products that support marine biodiversity monitoring and conservation. BioSound is particularly interested in understanding the value of underwater soundscape metrics as indicators of biological and anthropogenic change in the context of biodiversity conservation. BioSound was formed as an initiative of the Marine Biodiversity Observation Network (MBON). Additional information regarding the goals and objectives of the group can be found at the [MBON BioSound](https://marinebon.org/biosound/) site.

### **Exploratory Project**

The group's initial project begins with a focused initiative to compare acoustic-based biodiversity indices across various ocean environments, paving the way for a broader, more extensive analysis. These efforts aim to generate valuable data products highlighting biological sounds and habitat characteristics in regional ocean and coastal areas, while also providing recommendations for standardizing soundscape metric methods and enhancing standards within the bioacoustic community.

Explore the data collected during this pilot study via our dashboard:

#### [BioSound Data Exploration Dashboard](https://waveform-analytics.shinyapps.io/biosound-mbon/)

This data includes many things:

The Datasets

Environmental Data
